### PR TITLE
GC is turned off by default

### PR DESCRIPTION
**Pull request by thomasfanell**

### CODE REVIEW

**Comment by thomasfanell** [comment]
@fredrikbryntesson peer review?

**Comment by fredrikbryntesson** [comment]
What happens now if you compile with gc=off?

**Comment by thomasfanell** [comment]
@fredrikbryntesson gc=off has no effect

**Comment by thomasfanell** [comment]
I left it in there, since there might be cases where one wants to be explicit about the command line

**Comment by thomasfanell** [comment]
Perhaps we should remove everything related to GC, since we'll never use it.

**Comment by fredrikbryntesson** [comment]
If we run  `gc=off` this code will execute:
`params undefineSymbol(BuildParams GC_DEFINE)` in `rock/frontend/CommandLine.ooc` . Could this create any problems now when `BuildParams GC_DEFINE` is not defined?

**Comment by thomasfanell** [comment]
@fredrikbryntesson No, `undefineSymbol` performs an `indexOf` before attempting to remove. It's perfectly safe.

**Comment by fredrikbryntesson** [comment]
Great

**Pull request merged**
