### PR TITLE
Print version in preamble

### LINKED ISSUE #50: Print rock version in preamble
Now when compiling with rock it prints this preamble:
> magic-lang rock compiler

could be nice to have a version number there too
> magic-lang rock compiler (1.0.19-head)

@thomasfanell

### PR DESCRIPTION
**Pull request by shamanas**
Closes #50  

Prints stuff like `magic-lang rock compiler 1.0.18-head codename Freppasaurus Rex`

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Well that was quick :D

**Comment by shamanas** [comment]
Yeah, I felt like it was a priority ^^

**Comment by thomasfanell** [comment]
@shamanas very nice and quick indeed :-)
Do we want the full version string or just something like `magic-lang rock compiler 1.0.18` @fredrikbryntesson @sebastianbaginski @fredrikbryntesson ?

**Comment by fredrikbryntesson** [comment]
`magic-lang rock compiler 1.0.18`  is enough.

**Comment by sebastianbaginski** [comment]
@thomasfanell I'd just like to be able to see the version number, so either full string or just the version string is fine by me

**Comment by marcusnaslund** [comment]
I agree, version number is enough. :)

**Comment by fredrikbryntesson** [comment]
But  `Freppasaurus Rex` is a very nice name so it should be displayed a lot more :)

**Comment by shamanas** [comment]
Ok fixing now :P

**Comment by thomasfanell** [comment]
Excellent, thank you!

**Comment by sebastianbaginski** [comment]
Thanks :)

**Pull request merged**
